[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_ignores = True
disallow_untyped_defs = False
ignore_missing_imports = True
explicit_package_bases = True
namespace_packages = True
exclude = (?x)(
    ^\.venv/
    | ^htmlcov/
    | ^tests/
    | ^example_files/
    | ^gimmicks/
  )

[mypy-modules.*]
disallow_untyped_defs = True

[mypy-main.*]
disallow_untyped_defs = True

[mypy-modules.llm.langchain_provider]
disable_error_code = arg-type, call-arg, assignment

[mypy-modules.batch.backends.google_backend]
disable_error_code = index, attr-defined
