# chunking_config.yaml

chunking:
  default_tokens_per_chunk: 6250  # Chunk size (in tokens) for splitting the text into manageable pieces.
  # chunking_method defines the default method for splitting text into chunks.
  # Options:
  #   "auto"           - Automatic token-based chunking.
  #   "auto-adjust"    - Automatic chunking with an option for manual re-adjustments.
  #   "line_ranges.txt" - Use predefined line ranges from a corresponding _line_ranges.txt file. These files can be
  # created with "generate_line_ranges.txt" and then manually adjusted as needed.
  chunking_method: "auto-adjust"
